server:
  port: ${CRAWLER_PORT}

spring:
  application:
    name: crawler-service
  ai:
    openai:
      api-key: ${GEMINI_API_KEY}  # https://aistudio.google.com/apikey
      chat:
        base-url: https://generativelanguage.googleapis.com/v1beta/openai/
        options:
          model: gemini-2.0-flash-lite
          temperature: 0
        completions-path: /chat/completions

  data:
    mongodb:
      database: ${MONGO_DATABASE}
      uri: ${MONGO_URI}

firebase:
  secret:
    key:
      path: ${FIREBASE_KEY_PATH}