server:
  port: ${CRAWLER_PORT}

spring:
  application:
    name: crawler-service

  data:
    mongodb:
      database: ${MONGO_DATABASE}
      uri: ${MONGO_URI}

firebase:
  secret:
    key:
      path: ${FIREBASE_KEY_PATH}