server:
  port: ${CRAWLER_PORT}

spring:
  application:
    name: KNUTICE-CRAWLER
  ai:
    openai:
      api-key: ${GEMINI_API_KEY}  # https://aistudio.google.com/apikey
      chat:
        base-url: https://generativelanguage.googleapis.com/v1beta/openai/
        options:
          model: gemini-2.0-flash-lite
          temperature: 0
        completions-path: /chat/completions

  data:
    mongodb:
      database: ${MONGO_DATABASE}
      uri: ${MONGO_URI}

firebase:
  secret:
    key:
      path: ${FIREBASE_KEY_PATH}

logging:
  level:
    org:
      springframework.web: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus, metrics
  metrics:
    tags:
      application: ${spring.application.name}